### ISSUE TITLE
Error: spawn git ENOENT when clicking on a file in changeset

### ISSUE THREAD

**Issue by ubershmekel** [DonJayamanne/gitHistoryVSCode#143]
Hi, I'm using Git History (git log) 0.2.2 on VS Code June 2017 (version 1.14), on a Mac (Darwin yuvmac.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64)

I can see the log, and click on a changeset to see the list of changed files. When I click on a changed file I get a vscode toast saying:

>There was an error, please view details in the 'Git History Log' output window

The output panel says:
> [Info -14:05:33.139] git rev-parse --show-toplevel
> [Error-14:05:33.142] Error: spawn git ENOENT
> [Info -14:05:33.142] git repo path: /Users/bla/bla/bla.min

Maybe related to, but probably not: https://github.com/DonJayamanne/gitHistoryVSCode/issues/100

Otherwise it is a beautiful log, thank you for that.

**Comment by doggy8088** [comment]
I have the same issue on my Windows 10.

**Comment by rkeithhill** [comment]
Same here.
```
[Info -17:41:48.727] git rev-parse --show-toplevel
[Error-17:41:48.729] Error: spawn C:\Program Files\Git\bin\git ENOENT
```

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version

**Comment by lbogdan** [comment]
Was there a regression? I just installed this extension and keep getting the same errors:
```
git path identified as:  C:\Program Files\Git\bin\git
git rev-parse --show-toplevel  (completed in 0.003s)
{"stack":"Error: spawn C:/Program Files/Git/bin/git ENOENT\n\tat exports._errnoException (util.js:1050:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)\n\tat onErrorNT (internal/child_process.js:367:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:80:11)\n\tat process._tickCallback (internal/process/next_tick.js:104:9)","message":"spawn C:/Program Files/Git/bin/git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn C:/Program Files/Git/bin/git","path":"C:/Program Files/Git/bin/git","spawnargs":["rev-parse","--show-toplevel"]}
```

**Comment by strongui** [comment]
Same, error is back.

**Comment by borekb** [comment]
I uses Git for Windows under MSYS2, and get very similar errors. The extension output starts like this:

```
git path identified as:  git
git path identified as:  git
git path identified as:  git
git rev-parse --show-toplevel  (completed in 0.002s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
```

@DonJayamanne, do you think this issue could be reopened? Or should we create a new one?

**Comment by lbogdan** [comment]
@borekb This should be solved by #311 , waiting for @DonJayamanne to merge it.

**Comment by igor-h** [comment]
the same error is back!

{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}


VSCode Version: 1.28.1
Git History: Version 0.4.3
