### ISSUE TITLE
0.3.0 doesn't show history

### ISSUE THREAD

**Issue by SailorMax** [DonJayamanne/gitHistoryVSCode#182]
`View History` and `View File History` doesn't do anything. Possible after latest update.
Also `git log` doesn't highlight `View History` item anymore.

In development tools console I have: `Command `git.viewFileHistory` appears multiple times in the `commands` section.`

VSCode 1.19.2
Windows 10 1709 b16299.192

Extension|Author (truncated)|Version
---|---|---
scope-bar|amo|0.0.3
vscode-intelephense-client|bme|0.8.5
empty-indent|Dmi|0.2.0
githistory|don|0.3.0
gitlens|eam|7.5.3
php-debug|fel|1.12.1
code-runner|for|0.8.7
beautify|Hoo|1.1.1
python|ms-|0.9.1
vscode-nginx|sha|0.4.1
vscode-hexdump|sle|1.6.0
shell-launcher|Tyr|0.1.6

**Comment by DonJayamanne** [comment]
@mateuszwitkowski are you also on Windows?

**Comment by DonJayamanne** [comment]
Unfortunately I too can replicate this on Windows.

**Comment by mateuszwitkowski** [comment]
@DonJayamanne Yes.

**Comment by CarlosAzocar** [comment]
VSCode 1.20.0 - Insider
Confirmación: 54240a7bd3854fc9e0c07b399683547500a1914e
S.O: Debian GNU/Linux 8 (jessie) 64-bit

Same problem.

Development tool console output:
![captura de pantalla de 2018-01-17 06-33-50](https://user-images.githubusercontent.com/18235355/35038324-6505e314-fb72-11e7-93b8-6c156c843ee6.png)

**Comment by johnzhy** [comment]
on my windows 10  doesn't show history.
vscode:1.19.2
Git History: 0.3.0

![image](https://user-images.githubusercontent.com/17330192/35038784-ced2dbb4-fbb6-11e7-9764-0f829b8f07c0.png)

**Comment by DonJayamanne** [comment]
A fix is on the way, apologies for this.

**Comment by DonJayamanne** [comment]
Fixed. Apologies for the issues

**Comment by SailorMax** [comment]
@DonJayamanne 
`git log` still doesn't select "View History". Broken alias?

Plus History now has datetime in Russian. Why? I have english UI! Create another bug report?

**Comment by johnzhy** [comment]
@DonJayamanne 
Upgrade to Git History 0.3.2, but the problem persists.
![image](https://user-images.githubusercontent.com/17330192/35075792-184fd962-fc30-11e7-9558-b9837ee9fe64.png)

**Comment by DonJayamanne** [comment]
@johnzhy
What's your OS?
Please could you try running the commands printed out above, instead of `--format=<...>` , please use `--prettyprint=oneline`

**Comment by DonJayamanne** [comment]
Please try all for commands

**Comment by johnzhy** [comment]
OS: Windows 10 1709 16299.125
Git: git version 2.14.2.windows.3
Git install path on os: D:\Program Files\Git
Git path config on vscode : 
{
    "git.path": "D:\\\Program Files\\\Git\\bin\\\git.exe",
}
Running the commands:
![image](https://user-images.githubusercontent.com/17330192/35076959-cfd166be-fc35-11e7-9a56-c3755a27fefa.png)

**Comment by DonJayamanne** [comment]
Oops, please use `--pretty=oneline` not `--prettyprint=oneline` (my fault)

**Comment by DonJayamanne** [comment]
Please could you type in `chcp` in your command prompt. Thanks

**Comment by johnzhy** [comment]
![image](https://user-images.githubusercontent.com/17330192/35080967-ff9335a6-fc4b-11e7-8448-25afa097dd08.png)

FIND: The format of the parameter is incorrect.

**Comment by DonJayamanne** [comment]
Thanks for translating that.

**Comment by Haven09** [comment]
I have the same problem with Git History 0.3.2.
![1516331290 1](https://user-images.githubusercontent.com/19543302/35133366-da343e8a-fd0a-11e7-9d7d-0b7fc2fa8276.jpg)
But i can run the commands without `--format=<format>`.It seems can't find `format`

**Comment by ALongLi** [comment]
I have the same problem with Git History 0.3.2
`git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 main-xd-lal`
But when I try running the commands printed out above,it's ok

**Comment by Gavin110** [comment]
I have this problem with Git History 0.3.2
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 main-xd-lal

**Comment by DonJayamanne** [comment]
Fixed in latest version, will publish one soon
