### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by simonl65** [DonJayamanne/gitHistoryVSCode#233]
I get the following no matter what file I'm investigating:
```
git rev-parse --show-toplevel  (completed in 0.058s)
fatal: Not a git repository (or any of the parent directories): .git
```
This happens whether I have terminal open at the same location or not.

My seetings file includes:
```
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "git.path": "C:\\Program Files\\Git\\bin\\git.exe",
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "gitProjectManager.baseProjectsFolders": [
    "E:\\simonl\\Documents\\_dev"
  ],
```
There is definitely a .git folder at the level of the file being investigated.

**Comment by DonJayamanne** [comment]
If the got commands fail then it's not shot repo. Either way it's outside the scope of the extension. 
Please confirm u having opened a git folder. Opening a file within a git folder isn't sufficient. You need to open that folder within vscode.

**Comment by simonl65** [comment]
Yup - I opened the folder within VSCode's terminal and had it selected in the folder list on the left.
BTW: running `git rev-parse --show-toplevel` in the terminal responds with the folder path correctly.

**Comment by DonJayamanne** [comment]
Are you saying that it's working now?

**Comment by DonJayamanne** [comment]
> Yup - I opened the folder within VSCode's terminal 

If the folder was already opened in vscode, then this is unnecessary. Terminal will default to the same folder

**Comment by simonl65** [comment]
OK, so further investigation shows that I only get this if I have VSCode **open at a higher folder in the tree** e.g. at `C:\Users\simon\_dev` (see below). If I open VSCode at the root of the repo' (see _repo1_ below) everything works. Would it be possible for GitHistory to look for the .git that's **nearest the currently open file** instead of looking at the open root?
```
C:
+--Users
    +--simon
       +--_dev <--------------------------- VSCode open here
            +--WORK
                +-- repo1
                     |--.git
                     +--file-to-view.js <-- The file open when doing GitHistory
```

**Comment by simonl65** [comment]
Might this issue be a regression from issue #112 ?

**Comment by mhzed** [comment]
Same issue here.  But it was working fine before, and now all I get is "Not a git repository".  The only local change I remember is upgrading VS code to 1.19.3

**Comment by sshmyg** [comment]
+1

**Comment by simonl65** [comment]
Have just updated VSCode to 1.20.0 (Shell: 1.7.9, Renderer: 58.0.3029.110, Node: 7.9.0, Architecture: x64) and **problem persists**.

My **workaround** for the moment is to create a **multi-root workspace**. Now whenever I click the gitHistory button (top-right) it asks which root to use and all works OK.

**Comment by simonl65** [comment]
Might be related to #226?

**Comment by phantasm66** [comment]
+1

**Comment by Mykolas-Molis** [comment]
+1

**Comment by wolf99** [comment]
+1

**Comment by msvechla** [comment]
+1

**Comment by markus-wi** [comment]
+1

**Comment by arielf** [comment]
I had the same issue (even though I don't use VScode at all) and believe I figured out this bug.

Bug is triggered when `git` interacts with hooks that do a `chdir`/`cd` inside the hook process & then call `git rev-parse --show-toplevel` internally to figure out the git top level directory.

Just before calling any hooks, `git` sets several env vars, among them is one called `GIT_DIR` which points to the git index dir (if you're at the top level, it will be set to `.git` prior to calling your hooks)

The `GIT_DIR` setting becomes invalid when the hook does a `chdir` and calls `git` reentrantly to figure out the git top level dir.

This is because `git` seems to have an internal optimization:

     if $GIT_DIR is set, trust it and use it

My work-around was simple: inside my hook, just before calling `git rev-parse --show-toplevel` I make sure to `unset GIT_DIR` (hook is a bash script) so `git` doesn't get confused about which is its current directory.

No more errors after this simple work around.

**Comment by Huespal** [comment]
+1

**Comment by DonJayamanne** [comment]
@simonl65 @mhzed @Huespal @arielf @markus-wi @msvechla @wolf99 @phantasm66 @sshmyg @Mykolas-Molis This feature will land in the next release

**Comment by phantasm66** [comment]
Thanks!

**Comment by vahanNasibyan** [comment]
@DonJayamanne  any update on release status?

**Comment by hvedemelsbof** [comment]
+1 on v 0.4.1 in VS 1.25.0

**Comment by westhomas** [comment]
Great software! Very useful! This issue is my only complaint ;-)

**Comment by sonnyandersson** [comment]
Just got this issue. Feels like it was introduced by the latest update 1.25.1

**Comment by knapejor** [comment]
I have the same issue as sonnyandersson (now at Git History version 0.4.2 and VS Code version 1.26.1):

When opening Git History, selecting a commit and choosing 'compare against previous version', I get the following output:

`git log --pretty=oneline b120949045fca8fc35a8509d2df8ee67afb201fb^1 -n 1 -- ..\..\..\c:\www\xxx\file.php  (completed in 0.069s)`

`fatal: ..\..\..\c:\www\xxx\file.php: '..\..\..\c:\www\xxx\file.php' is outside repository`

When choosing 'Compare against workspace file', an errors pops up with message **'Corresponding workspace file does not exist'**.

This functionality was working fine up until a few weeks ago.

**Comment by LbISS** [comment]
Same problem again with 1.26.1...

**Comment by unional** [comment]
I would vote for reopening this issue because it is happening on 1.26.1

**Comment by GreggJensen** [comment]
+1

**Comment by aiyyoi** [comment]
+1 for reopen this issue

**Comment by blachawk** [comment]
This needs to be reopened!

**Comment by abeusher** [comment]
+1 vote to re-open.  This is happening to me.  (11 September 2018).

**Comment by LbISS** [comment]
@DonJayamanne Could you please reopen this issue? It's reproducing again.

**Comment by jamolina** [comment]
I have the same issue when using 'compare against previous version'

**Comment by adil1214** [comment]
+1, still the same error "Corresponding workspace file does not exist" on version 0.4.2 VSCode version 1.27.2.

**Comment by gcuevas82** [comment]
+1 same

**Comment by ole1986** [comment]
@gcuevas82 can you please post the complete error?!

**Comment by knapejor** [comment]
> @gcuevas82 can you please post the complete error?!

The error that I placed before is still there:

When opening Git History, selecting a commit and choosing 'compare against previous version' for a file, I get the following output:

```
git log --pretty=oneline b120949045fca8fc35a8509d2df8ee67afb201fb^1 -n 1 -- ..\..\..\c:\www\xxx\file.php (completed in 0.069s)

fatal: ..\..\..\c:\www\xxx\file.php: '..\..\..\c:\www\xxx\file.php' is outside repository
```

When choosing 'Compare against workspace file', an errors pops up with message 'Corresponding workspace file does not exist'.

**Comment by jamolina** [comment]
Not sure if it helps but, I was still having this issue when I noticed this message on the `OUTPUT` tab (edited to a different branch name for privacy). Note that my branch is actually called `feat/123/myFeature`

```
git remote get-url origin/feat/123  (completed in 0.049s)
fatal: No such remote 'origin/feat/123'
```

I switched to our `master` branch (which does not have any slashes"/") and tried to do a compare against previous and it worked! When I switched to my `feat/123/myFeature` branch, I still got the same error (No Such remote) but the compare against previous was working now.

**Comment by knapejor** [comment]
I'm not sure what did happen but everything started to work like normal yesterday afternoon.
In the morning the problem was still there, (When I placed my previous post / comment, I checked)

No updates / change logs can be seen but also no changes to our systems were made regarding to this, and it now works on all our repositories.

Can anyone else having these problems check this functionality?

**Comment by LbISS** [comment]
@knapejor 
I've found that this bug have been fixed in version 0.4.3, it was released 4 days ago and your VS code have automatically updated extension.
https://github.com/DonJayamanne/gitHistoryVSCode/pull/316
https://github.com/DonJayamanne/gitHistoryVSCode/releases/tag/0.4.3

**Comment by gitkent** [comment]
Just installed this extension on Mac OSX Mojave still getting the below error when I click View Line History (same for View File History):

```
git rev-parse --show-toplevel  (completed in 0.013s)
fatal: not a git repository (or any of the parent directories): .git
```

running on:
```
$ ▶ git --version
git version 2.20.1 (Apple Git-117)

VS Code - version 1.36.1
Git History - version 0.4.6
```

Can someone please assist?

**Comment by frimik** [comment]
Something in newer vscode versions(?) sets `GIT_DIR` environment variable to the value `.git` which makes git not behave well as it used to do in the vscode terminals.

```sh
(jobs) ➜  git status
fatal: not a git repository: '.git'
(jobs) ➜  echo $GIT_DIR
.git
```

git then only functions in the git repo top directory, not any of the subdirectories.

**Comment by Domae84** [comment]
Does anybody has a solution for this bug?

My Folder structure looks like this: folder1>webapp>project>.git
When I open VSCode from folder1 I get the following error:
`git rev-parse --show-toplevel  (completed in 0.082s)
fatal: not a git repository (or any of the parent directories): .git`

When I open the folder with the .git folder, everything works fine.

Can someone please assist here?

**Comment by peinrules** [comment]
You should first run `git init` in your current directory.

**Comment by zhanls** [comment]
I also meet the same problem today. Google and searched for one hour but failed to solve it. Really frustrated

**Comment by nasIndustrie** [comment]
> You should first run `git init` in your current directory.

Thanks!

**Comment by MightBeHarmless** [comment]
[This VS Code Issue](https://github.com/microsoft/vscode/issues/4651) by mattn in 2016, assisted me with a problem occurring in 2020 with VS Code not being able to properly handle output of the `git rev-parse --git-dir` command.

I modified the proposed git-wrap.bat to make the last line:
`for /f %%1 in ('git %*') do cygpath -wa %%1` to enforce the full path is returned always to Code.

After hooking in the bat file in place of the git.path target, SCM started to function, for the first time.
So, in addition to checking for proper PATH settings, please consider these steps in debugging your path formats.

I am using msys2 (mingw64) versions of git binaries in place of Git for Windows, which seemed too redundant to me. Though it must be considered that whatever simplification they set in place, it permits many users to avoid this troubleshooting. Win 10. Not using the project of DonJayamanne at all. Just interested in helping any users who are similarly challenged as I was.
