### ISSUE TITLE
Do not reload Git history tab after switching to another

### ISSUE THREAD

**Issue by Avol-V** [DonJayamanne/gitHistoryVSCode#51]
Do not reload Git history tab after switching to another, or remember position and selected commit.
It's very difficult to explore commits when after viewing changes in file and switching back you loose your position.

**Comment by DonJayamanne** [comment]
I too noticed that last week and will fix that for the next release. Agreed, personally that's a Horrible ux and annoying

**Comment by mikes-gh** [comment]
I just tested this with vscode insiders build (will be 1.8) which has electron 1.4.6 and this is still an issue.
Any ideas anyone?

**Comment by DonJayamanne** [comment]
This is an issue upstream (VS Code) issue. (https://github.com/Microsoft/vscode/issues/5257)
I don't believe it has been resolved in VS Code (not to my knowlege)

**Comment by mst-dev** [comment]
As of now the issues still exists. Any updates?
This extension is very critical for me with Git.

**Comment by mst-dev** [comment]
I have a suggestion for this.
If file comparison and other actions the extension does by opening a new tab is opened in split view, this will keep git history tab open and no need to reload when returning back.

This will at least help when viewing file comparisons and coming back to the history list.

**Comment by DonJayamanne** [comment]
Fixed in latest release (it sill reloads but it remembers where you were)
