### ISSUE TITLE
Can not open "file history" view if path has a plus sign

### ISSUE THREAD

**Issue by gdh1995** [DonJayamanne/gitHistoryVSCode#556]
For example, if I have a repo at `E:\Git\weidu+vim\vimium-c`, and use `Git: View File History` of this extension, then it will opens a blank page, and the output panels shows:
``` bash
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 master --follow -- ../../weidu vim/vimium-c/content/local_links.ts  (completed in 0.062s)
fatal: ../../weidu vim/vimium-c/content/local_links.ts: '../../weidu vim/vimium-c/content/local_links.ts' is outside repository at 'E:/Git/weidu+vim/vimium-c'
```

It seems that `weidu+vim` is translated into `weidu vim`, and then it fails.

**Comment by ole1986** [comment]
This is possibly fixed with version 0.6.7?!

**Comment by gdh1995** [comment]
No. I just updated it to v0.6.7 but this issue is still there, and the error message is unchanged.

**Comment by ole1986** [comment]
Fixed in v0.6.8

**Comment by gdh1995** [comment]
Confirmed that this has been fixed.
